import Head from 'next/head'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Sidebar/>
           <h2>Learn </h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
  
    </div>
  )
}
